lib/App.js
lib/App.server.js

Recent changes to derby introduced ```serverOnly``` templates which can't be updated on the client and ```Styles:``` is one of them. 
This pull request fixes the autoreload issues with styles by marking ```<style>``` tag with related filename and replacing its content when the time comes to update it.

Fix live update of styles.

---

lib/App.server.js

This will allow derby plugins (`app.use()`) to access browserify instance to bundle in additional client-side scripts / register additional transforms.

Emit 'bundle' event on app

---

lib/documentListeners.js
test/browser/bindings.mocha.js

Bugs that were fixed:
* In any version of Trident, number inputs' `valueAsNumber` property are always `NaN` for some reason, so in those situations I fell back onto getting the value from `parseFloat(input.value)`
* Sliders in IE fire `change` events instead of `input` events when they change, so I added code for handling those cases into the `change` listener.
* Deleting text in IE9 doesn't fire `change` or `input` events, so I added listeners for `selectionchange` events. It fires aggressively but it's the only sane way of ensuring we catch any field updates.
* One of the test cases didn't work in IE due to required arguments missing, so I fixed it

Cross browser fixes

---

.pre-commit-config.yaml

An attempt to make compliance with the [style guide] easier for the rest
of us. Will not impact anyone who has not explicitly run `pre-commit install`
on this repo. For more, see http://pre-commit.com/
[style guide]: https://github.com/lever/style-guide

add config for yelp pre-commit

---

lib/documentListeners.js

/cc @nateps @enjalot 
This was a regression due to my cross browser changes. The solution was to get the value from `inputValue(target)` when working with a value binding rather than setting it directly, since `inputValue(target)` ensures that it gets cast to the correct type in the case of number fields.
(fixes #492)

Fixed bug where number inputs would be cast to strings sometimes

---

lib/components.js

This is fix for the issue https://github.com/derbyjs/derby/issues/482. Just added updateIndices option to component attribute reference.

Components attributes binding fix (passing attributes which are array items)

---

lib/App.server.js

In producton I have the next HTML structure in head tag
```html
<head>
<style data-filename="/home/www/project-name/apps/app-name/styles/../../../public/css/bootstrap.css">
<style data-filename="/home/www/project-name/apps/app-name/styles/index.styl">
<style data-filename="/home/www/project-name/components/component-name/index.styl">
</head>
```
I think, it's not correct to show file system path. It could be used in dev environment, but not in prod.
Maybe method _loadStyles should be improved for using file location for site.

Improvement. Do not display system filepath to css file in production

---

lib/App.server.js
lib/Page.server.js

@nateps 
As we discussed, track a bit on the model when we handle a model error.
Then, in the Page.render check for this bit so we don't render the page

Do not render when model has errored

---

lib/App.server.js

node v6 changed path.dirname to throw if the input path is not a strng.
In versions of node < 5, `path.dirname(undefined)` is equivalent to `path.dirname('')`. 
By falling back to `''` before calling dirname, we are able to maintain consistent behaviour across all versions of node

Node v6 compatibility 

---

lib/App.server.js

In development mode, `App#writeScripts` tries to clean up old script bundles for the app being bundled.
However, it currently doesn't correctly handle app names with dashes. The bundles for such apps look like "demo-app-1234abc.js" and "demo-app-1234abc.map.json", which means the `filenames[i].split(/[-.]/)` extracts an app name of "demo" and a script hash of "app".
This switches to checking for matching app name / script hash prefixes with `indexOf`, which correctly matches app names with dashes (and dots).

Bundle cleanup (non-production): Correctly clean up app names with dashes

---

.travis.yml
lib/documentListeners.js

Addresses: https://github.com/derbyjs/derby/issues/516
> The Travis badge says "build unknown", but it should say "build passing". This would help improve the image of the project, and would make it more appealing for potential adopters.
I reactivated Travis for Derby and updated the config to run tests for Node v4 and v6.
The jslint step was failing because 
```
lib/documentListeners.js: line 51, col 5, Reassignment of 'inputValue', which is is a function. Use 'var' or 'let' to declare bindings that may change.
```
So the code change is to fix that linting error.

Run Travis CI for Node v4 and v6

---

lib/components.js

Don't overwrite the current base class but rather add Component as a new base class to the end of the prototype chain. If we overwrite the immediate base, we break ES6 classes and inheritance, especially if used with babel. Babel adds the following check:
```
function _classCallCheck(instance, Constructor) { 
if (!(instance instanceof Constructor)) { 
throw new TypeError("Cannot call a class as a function");
}
}
```
That breaks with the current Derby implementation since Constructor will be changed to Component instead of the original class.

fixed extendComponent(): it now also works with ES6 classes

---

lib/Page.js
test/browser/bindings.mocha.js

This fixes a bug in binding updates, triggered when a model listener causes a change to the path being listened on.
See the new test for more details.
Preliminary app testing all seems fine, but to be safe, I'm putting this behind a flag. To enable the new behavior, do a `model.set('$derbyFlags.immediateModelListeners', true)` before calling `app.createPage()`.
I intend to remove the flag in a month or so, after we do some more internal testing with the flag on.

Switch to immediate model listeners

---

lib/Page.js
test/browser/bindings.mocha.js

During integration testing of the original implementation of `immediateModelListeners` in https://github.com/derbyjs/derby/pull/554, we discovered a couple feature regressions relating to binding updates. Good thing I decided to put it behind an opt-in flag!
The regressions turned out to both be manifestations of the same issue - a mutation on a path with a numeric segment wasn't updating bindings. `EventModel#update` checks `typeof` for path segments, and the implementation of immediate model listeners wasn't calling `castSegments` to convert numeric string segments into JS numbers.
This PR fixes the issue by using `castSegments` like the current non-immediate listeners do, and I've adds a new test for the case of binding updates with numeric segments.
Side note - …

Fix binding update regression with immediateModelListeners flag on

---

lib/components.js
package.json
test/all/eventmodel.mocha.js
test/browser/as.mocha.js
test/browser/bindings.mocha.js
test/browser/components.js
test/browser/dom-events.mocha.js
test/browser/forms.js
test/browser/util.js

Implement new prototype methods of Component that help to avoid bugs & memory leaks in async callbacks. Introduces the following methods:
* `fn = component.bind(callback)` – Returns a function that is bound to the component, similar to `fn = callback.bind(component)`. In addition, when the component is destroyed, stops calling the callback and removes its references to the component and the callback. This makes it simpler to avoid bugs that could occur if async functions executed after the component was removed from the page, and it helps to reduce memory leaks if the reference to the returned function is held by some other code outside of the component. Internally uses Function::apply, so not as performant as fat arrow functions, but it is a simple way to add a lot of safety around async …

Component::bind(), throttle(), debounce(), and debounceAsync()

---

lib/Page.js
test/browser/bindings.mocha.js

Add support for racer emitting event objects instead of args lists. Feature detect so that Derby can be compatible with both. Plan to change Racer to the new format in a patch version, since these events are considered internal, and they should only be used within derby & racer.

Model event objects

---

lib/App.js
lib/parsing/index.js
package.json
test-utils/ComponentHarness.js
test-utils/assertions.js
test-utils/index.js
test/all/ComponentHarness.mocha.js
test/browser/as.mocha.js
test/browser/bindings.mocha.js
test/browser/components.js
test/browser/dom-events.mocha.js
test/browser/forms.js
test/browser/util.js

1. This PR adds a new preferred format for specifying the view associated with a component with an object. (See below for examples.) The goal is to allow the view of a component to be inlined in JavaScript as a string, primarily for mocking components in tests. Use of inline view source is discouraged in production application code, which should use external files for views.
Examples:
```js
class Box {
static view = {file: __dirname};
}
```
```js
class Box {
static view = {
is: 'box',
file: __dirname
};
}
```
```js
class Box {
static view = {
is: 'box',
source: `
<index: attributes="foo bar">
<div class="box">
{{@content}}
</div>`
};
}
```
2. Components can now specify their dependencies on other components! Now, calling `app.component()` will recursively register other components needed …

Component.view, component dependencies, and test utils

---

test-utils/ComponentHarness.js
test/dom/ComponentHarness.mocha.js

JSDOM doesn't support window navigation, but thankfully Derby apps often use Derby's routing, which is in tracks.
That means we can fake out `app.history` in the ComponentHarness. This PR specifically adds fakes for `app.history.push(url)` and `app.history.replace(url)`, which are usually defined in https://github.com/derbyjs/tracks/blob/v0.5.8/lib/History.js

ComponentHarness: Fake implementations of app.history #push and #replace

---

lib/App.js

Quick fix for issue #571. Not sure if there is a more elegant way to do this, but this seems to work well.

fix #571 - don't check component dependency override when deserializing

---

lib/App.js
package.json
test-utils/ComponentHarness.js
test/all/ComponentHarness.mocha.js

add support for passing view source to harness.stub()
use the array of name and source, which is analogous to the syntax of component dependencies

Stub with source

---

test-utils/domTestRunner.js
test/dom/domTestRunner.mocha.js

This adds support for passing in JSDOM constructor options to `domTestRunner`.
For example, this is how to pass the `pretendToBeVisual: true`, which enables use of `window.requestAnimationFrame` in JSDOM - [see JSDOM readme](https://github.com/jsdom/jsdom#pretending-to-be-a-visual-browser):
```,
domTestRunner.install({
jsdomOptions: {
pretendToBeVisual: true
}
});
```
Derby itself doesn't use `requestAnimationFrame`, so its own tests don't need it. Plus it's useful for a test to be able to customize JSDOM options if needed.

domTestRunner: Add support for passing JSDOM options

---

lib/AppForServer.js

This will fix the warnings `ShareDBError: Invalid or unknown message` logged by ShareDB's Agent, which resulted from Derby auto-refresh using ShareDB's messaging mechanism. The warnings started happening after https://github.com/derbyjs/derby/pull/560.
Credit to @IAkumaI for this approach, described here:
https://github.com/derbyjs/derby/pull/568#issuecomment-577446978
I just did a small modification to use a plain EventEmitter event for the second layer of dispatch, instead of using another ShareDB middleware action. That way Derby has full control over the event format.
I also added comments explaining how auto-refresh works.

Fix ShareDB "Invalid or unknown message" warnings when using auto-refresh

---

test-utils/ComponentHarness.js
test-utils/assertions.js
test/dom/ComponentHarness.mocha.js

* In failure messages, state whether it was the HTML or DOM rendering that failed.
- This makes it easier to debug test failures.
* `.to.render()` - Compare DOM rendering to the HTML before components' `create()` methods are called.
- This fixes an issue where the assertion was improperly failing when a component modified its DOM in `create()`.
* Normalize HTML before comparisons.
- This fixes an issue where `.to.render()` assertions would fail when templates used HTML entities like `&nbsp;`.

Improve test-utils assertions

---

lib/components.js
test-utils/ComponentHarness.js
test-utils/domTestRunner.js

1. Fix a `Component#destroy` error when no components on the page use bindings.
- If no components on the current page use bindings, then `Component#destroy` would fail due to `this.page._eventModel.object` not existing, since `_eventModel.object` [starts off null](https://github.com/derbyjs/derby/blob/4e6bbb52da510dddc0767f1c8bf5ee9939e7b201/lib/eventmodel.js#L98) and [is lazily initialized when a binding needs it](https://github.com/derbyjs/derby/blob/master/lib/eventmodel.js#L160).
- This fix guards against that case. There's no need to clean up `.object` if it was never initialized.
2. For test-utils, ComponentHarness now tracks the pages it creates, and the DomTestRunner then uses that to destroy the created pages in an `afterEach`.
- This prevents silent post-test errors like …

Fix Component#destroy error when no bindings exist, update test-utils to call Page#destroy

---

lib/Page.js

Using derby <= 0.10.29 with racer@1.0.0, there is an issue where highlighting some bound text and typing over it (replacing it) causes the cursor to jump to the end of the input field.
The cause is a typo in the new `changeImmediate` listener, using `event.pass` instead of the correct `event.passed`.
Say you have "hey there" in a text box, select the "ey", then type "i" to change it to "hi there". There are two Derby events, a string remove of the "ey" and a string insert of "i".
The missing `passed` data causes the text bindings to not use the special text-update handlers here:
https://github.com/derbyjs/derby/blob/09d2a708d664ca3f530db748af3a7a1e378e4a89/lib/Page.js#L392-L410
Instead, the bindings fell back to a DynamicAttribute update, which for the remove does a `input.value = 'h …

Fix typo in changeImmediate listener for event.passed

---

lib/App.js
test/all/App.mocha.js

Parse errors from JSON.parse() to add useful context on unexpected token errors.
On `_finishInit()` calls, if the `innerHTML` of the app state element is invalid JSON, then an unhelpful error like `Uncaught SyntaxError: Unexpected token h in JSON at position 13540` is all the context you have. This parsing is done to rehydrate the app state as written by https://github.com/derbyjs/derby/blob/master/lib/PageForServer.js#L83-L94 which does some escaping of the string to prevent the script tag from being prematurely closed

Add context to error on Unexpected token error

---

test/dom/bindings.mocha.js

As part of moving to ESLint in the derby-2 branch, there was refactoring that introduced an issue with view functions using array items as one of many arguments, e.g. `viewFn(#item, someOtherPath)`:
https://github.com/derbyjs/derby/pull/604/files#diff-466e85435a395f659e185303f111e9c7a0e4dd4f3e08400eed586fabb0814141R260
The bug was fixed in ba742f6712dfaca2f6255789dfc6a924728ebf78.
This adds a behavioral binding test that failed without the bugfix, and now passes with the bugfix included.
I'm not entirely certain how the presence of the second param triggered the bug. I suspect it's something related to the dependency structure being different with two+ params instead of just one param.

Add behavioral test for binding bug with view function calls on array items

---

lib/components.js

- Add component wrapper methods for `window.requestAnimationFrame` and `process.nextTick`
In some situations components can be disposed of before callbacks are triggered when invoked when provided to `window.requestAnimationFrame` and `process.nextTick` This adds methods on the components to safely ignore callbacks if component has already been destroyed.

Safe `requestAnimationFrame` and `nextTick` methods

---

.github/workflows/test.yml
.gitignore
lib/App.js
lib/AppForServer.js
lib/PageForServer.js
lib/bundler/index.js
package.json

- add registration of apps in global namespace
- add name to app state element
- use name to fetch app state

Derby2 pre-webpack changes

---

lib/App.js

Move require of views to `init()` function and call `_views()` to get module, allowing override of method via other plugins (notably `derby-webpack`)

Dynamic app views

---

lib/App.js
package.json

Hot module reload causes a new app instance to be created. To prevent multiple instances of the same app from manipulating the same data, destroy the previous instance's active page before initializing components on the new instance.

In hot module reload, destroy previous app's page

---

.eslintrc
lib/App.js
lib/Page.js
lib/components.js
lib/eventmodel.js
lib/parsing/createPathExpression.js
lib/parsing/index.js
lib/parsing/markup.js
lib/templates/contexts.js
lib/templates/dependencyOptions.js
lib/templates/expressions.js
lib/templates/index.js
lib/templates/operatorFns.js
lib/templates/templates.js
lib/templates/util.js
package.json
test/all/parsing/dependencies.mocha.js
test/all/parsing/expressions.mocha.js
test/all/parsing/templates.mocha.js
test/all/parsing/truthy.mocha.js
test/all/templates/templates.mocha.js
test/browser/components.js
test/browser/util.js
test/dom/templates/templates.dom.mocha.js
test/server/templates/templates.server.mocha.js

- Move code and tests from saddle, derby-templates and derby-parsing into main derby repo
- The three commits that start with "Move ..." are pretty much copy/paste, so they can be skipped when looking at commit diffs.
- Fix lint issues with merged-in code, since the other three repos were using old lint rules and didn't have CI to enforce lint correctness
- Switch to using JSDOM for DOM-based tests from the three repos, which enables them to run in our current GH Actions CI instead of needing to be manually run in a browser
- Fix `npm run lint` and `npm run test` scripts to correctly pick up all files
- Make App.js ES5-compatible again
- For hot reload supporting code, switch from `Map` to a plain JS object, and from `globalThis` to `global`.
- We can switch back once we officially drop …

Merge saddle, derby-templates and derby-parsing into main derby repo

---

lib/App.js

Use environment variables to set `scriptHash`, `bundledAt`, and add new attribute `buildVersion`

Use env vars to set version strings

---

src/PageForServer.ts

Unifying the `Page.render` and `PageForServer.render` args resulted in changing arg order so `status` is last optional arg. 
This removes the now incorrect var ags handling for `PageForServer.render`

Remove vargs check as arg order switched to match client Page

---

.github/workflows/docs-gh-pages.yml

- We need to run `bundle install` inside the `docs/` directory
- I've also enabled gem caching in the setup-ruby action, which should help speed up install times
- To help ensure docs changes are valid, allow the workflow to run on all branch pushes, instead of just the default branch
- Add conditionals so that only default branch pushes will run the upload and deploy steps
- Add `DOCS_DIR` variable for the docs directory, so we don't have to repeat it throughout the workflow

[docs] Fix Pages build, update workflow to trigger build-only on branches

---

lib/App.js
test/dom/components.mocha.js

Same as https://github.com/derbyjs/derby/pull/627, but based on and merging into pre-TypeScript `v2` branch, to fix it for code using Derby v2.

[derby@2] Fix bug registering component with static `view.is` prop but no `view.file` prop

---

.eslintrc
src/App.ts
src/PageForServer.ts
src/components.ts
src/eventmodel.js
src/parsing/createPathExpression.ts
src/parsing/index.ts
src/templates/expressions.ts
src/templates/templates.ts
src/templates/util.ts
test/dom/bindings.mocha.js

In several places, strings used as object keys can cause prototype pollution. While these strings are almost always developer-controlled, not end-user-controlled, it's still good to be defensive.
This guards against the key "__proto__" and all keys on `Object.prototype`, which includes "constructor".

Guard against prototype pollution

---

src/PageForServer.ts

Broke it in https://github.com/derbyjs/derby/pull/630 - I misunderstood the second param to `Object.create`.

Fix error in server app.renderStatic

---

package.json

Some modules in derby, like test-utils, are not accessible from the root package export. TypeScript with the default classic moduleResolution (pre `"node16"`) doesn't use the package.json `exports` field, so the only way to use such modules is by using the `dist` paths, e.g. `'derby/dist/test-utils'` instead of the exports-mapped `'derby/test-utils'`.
This adds package.json `exports` `dist/*` paths for a selection of such modules that are useful in consumers.

Add package.json exports for derby/dist/{components,parsing,templates,test-utils} for compat with TS classic moduleResolution

---

src/test-utils/ComponentHarness.ts

Fixes `ComponentHarness` methods `renderHtml` and `renderDom` not having optional `options` argument
Additionally `renderHtml` and `renderDom` both returned `PageForHarness` which left relevant `html` or `fragment` attributes as nullable. This adds return types for each method with appropriate non-null attribure (e.g. `html: string` for `renderHtml`)

Make RenderOptions optional

---

package.json
src/server.ts

Downstream code failing when using `derby/server` as `cluster` imported in trasformed with `default` import like this:
```
// there is no cluster.default
if (cluster.default.isPrimary) {
console.log('Primary PID ', process.pid);
startWorker();
}
```
and erors with `default is undefined`
Additionally added forward compatible mapping for pre node16 module resolutions for server

Fix derby/server cluster imports

---

src/test-utils/ComponentHarness.ts

Updating the input type of `stub` function to allow `source` property to be passed in.   This change allows other TS files calling `harness.stub` to pass in a view source to `harness.app.views.register`.  If `source` isn't passed in, `stub` will continue to register with a view of `''`. 
https://github.com/derbyjs/derby/blob/37e41363bf3733921529f6bbb4888f859c652734/src/test-utils/ComponentHarness.ts#L132

Add source as optional param to stub

---

docs/guides/troubleshooting.md

This is meant to be a guide to help Derby users to troubleshoot problems they may encounter.

introduce a troubleshooting guide for Derby

---

package.json
src/App.ts
src/AppForServer.ts
test/all/App.mocha.js

While the App's "ready" and "load" events provide the app's current Page instance when emitted, those events only fire a single time per App instance.
There are a couple scenarios where an App instance can create a new Page instance after initial load:
* A full client-side route change inside the app (non-transitional route)
* A code-initiated client page refresh with `app.history.refresh()`
That means an app can't rely on the "ready" and "load" events to do custom initialization on Page instances.
To allow such customizations, this adds a new "page" event, emitted each time an app creates new Page instances.
Note - this new event is emitted both during server-side rendering, as well as during client-side initialization and page changes.

Add new App event "page", emitted when a new Page instance is created

---

docs/README.md
docs/_config.yml
docs/apps.md
docs/models.md
docs/models/backends.md
docs/models/contexts.md
docs/models/events.md
docs/models/getters.md
docs/models/mutators.md
docs/models/paths.md
docs/models/queries.md
docs/models/reactive-functions.md
docs/models/refs.md

- Overall:
- Document `*Promised` methods added in racer@1.1.0, with examples
- Change the very outdated "store" term to use "backend" instead
- Main Models page:
- Add textual overview of important sub-pages
- Rewrite docs on creating models for clarity
- Add docs for `model.close()`
- Contexts:
- Small rewrites for clarity
- Events:
- Recommend that new code use `{useEventObjects: true}`
- Mention that TS types only support that event-objects callback format
- Hide full docs on legacy event callbacks by default
- Getters:
- Add docs for `getOrThrow` and `getOrDefault` added in racer@2.1.0
- Make a louder warning about in-place modififications of values returned by non-copying `get*` methods
- Mutators:
- Add section about error handling
- Rewrite info about confirming mutations, now in …

[docs] Improvements to Racer model docs

---

docs/components/lifecycle.md
docs/guides/troubleshooting.md
src/components.ts
test/dom/components.mocha.js

Run-time troubleshooting improvements
- In development, warn if a component's init() is improperly an async or Promise-returning function
- Eagerly throw error if registering a singleton component that extends Component, instead of at render-time throwing an obscure "Uncaught TypeError: Cannot read properties of undefined (reading 'controller')"
New doc sections in [Troubleshooting guide](https://derbyjs.github.io/derby/guides/troubleshooting) for errors
- Error when using local model paths in singleton components
- "Mutation on uncreated remote document"
- "Invalid op submitted. Operation invalid in projected collection"
Tests
- New tests for singleton components

Troubleshooting improvements for components and errors

---

.github/workflows/docs-gh-pages.yml
.gitignore
docs/_config.yml
package.json
src/Controller.ts
src/components.ts
src/routes.ts
src/templates/contexts.ts
src/test-utils/ComponentHarness.ts
typedoc.json
typedocExcludeUnderscore.mjs

- Add Typedoc setup for generating API docs
- Integrate API docs into jekyll build process w github actions

Add Typedoc generated API docs

---

.github/workflows/docs-gh-pages.yml
.gitignore
docs/_config.yml

Jekyll was clobbering API doc output form Typedoc. Fixed w correct `keep_files` in jekyll config. Additionally, streamlined action steps - used `working-directory` and removed redundant `bundle install` handled by ruby setup step

Fix doc site api-doc generation

---

docs/_sass/custom/custom.scss
docs/views/template-syntax/view-attributes.md

Add documentation for `as-array` and `as-object`

Document as-array and as-object

---

src/App.ts
src/AppForServer.ts

Add `script*` options to `AppOptions` as referenced by AppForServer

Update AppOptions to include script* attributes 
